include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "lib/core/di/injectable.config.dart"
    
  errors:
    missing_required_param: warning
    missing_return: warning
    
linter:
  rules:
    constant_identifier_names: false