name: joke_app
description: "Joke Generator Mobile Application"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  hydrated_bloc: ^9.1.4
  path_provider: ^2.1.2

  equatable: ^2.0.5
  injectable: ^2.3.2
  get_it: ^7.6.7
  
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  
  either_dart: ^1.0.0
  dio: ^5.4.1
  
  chucker_flutter: ^1.6.3
  skeletonizer: ^1.1.0
  connectivity_plus: ^5.0.2
  go_router: ^13.2.1  

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
